replicaCount: 2

image:
  repository: ghcr.io/watt-is-up/powerport-provider-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

env:
  ASPNETCORE_ENVIRONMENT: "Production"
